In [4]:
import numpy as np

In [271]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])

a

array([ 4, 10, 12, 23, -2, -1,  0,  0,  0, -6,  3, -7])

In [264]:
# 1. How many negative numbers are there?

a < 0
mask =a < 0
a[mask]
# array([False, False, False, False, False, False, False, False, False, False])

count_neg_numbers = mask.sum()
count_neg_numbers


4

In [266]:
# 2. How many positive numbers are there?
# A: 5, excluding all zeroes

a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
b = a > 0
b
# array([ True,  True,  True,  True, False, False, False, False, False, False,  True, False])

count_pos_numbers = sum(b)
count_pos_numbers

5

In [105]:
# 3. How many even positive numbers are there?
    #A: 3, excluding all zeroes
    
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])
is_even = a % 2 == 0
is_even
# array([ True,  True,  True, False,  True, False,  True,  True,  True,
#True, False, False])

is_pos_even = b & is_even
is_pos_even
#array([ True,  True,  True, False, False, False, False, False, False,
#False, False, False])

a[is_pos_even]
len(a[is_pos_even])
#3

3

In [102]:
# 4. If you were to add 3 to each data point, how many positive numbers would there be?
    # A: 3
c = a + 3
c
#array([ 7, 13, 15, 26,  1,  2,  3,  3,  3, -3,  6, -4])

d = c > 0
d
# array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
# False, True, False])

a[d]   
#array([ 4, 10, 12, 23, -2, -1,  0,  0,  0,  3])
len(a[d])
#10

10

In [110]:
# 5. If you squared each number, what would the new mean and standard deviation be?
    # A: mean = 74.0, std dev = 144.0243
    
#Step 1: Square each number in the array
a_squared = a ** 2
a_squared
#array([ 16, 100, 144, 529,   4,   1,   0,   0,   0,  36,   9,  49])

#Step 2: Find new mean and standard deviation
np.mean(a_squared), np.std(a_squared)
#(74.0, 144.0243035046516)


(74.0, 144.0243035046516)

In [113]:
# 6. A common statistical operation on a dataset is centering. This means to adjust the data such that the mean of the data is 0. This is done by subtracting the mean 
#from each data point. Center the data set. See this link for more on centering.
    # A: see below
center = a - np.mean(a)
center
# array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
 #      -10.])

array([  1.,   7.,   9.,  20.,  -5.,  -4.,  -3.,  -3.,  -3.,  -9.,   0.,
       -10.])

In [267]:
# 7. Calculate the z-score for each data point.
    # A: see below
z_score = (a - np.mean(a))/np.std(a)
z_score

array([ 0.12403473,  0.86824314,  1.11631261,  2.48069469, -0.62017367,
       -0.49613894, -0.3721042 , -0.3721042 , -0.3721042 , -1.11631261,
        0.        , -1.24034735])

In [ ]:
# 8. Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py and add your solutions.


In [ ]:
import numpy as np
# Life w/o numpy to life with numpy

## Setup 1
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

In [274]:
a = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
# Exercise 8.1.1 - Make a variable called sum_of_a to hold the sum of all the numbers in
#above list
    # A: 55
sum_of_a = np.sum(a)
sum_of_a

55

In [118]:
# Exercise 8.1.2 - Make a variable named min_of_a to hold the minimum of all the numbers in
#the above list
    # A: 1
min_of_a = np.min(a)
min_of_a

1

In [119]:
# Exercise 8.1.3 - Make a variable named max_of_a to hold the max number of all the numbers 
#in the above list
    # A: 10
max_of_a = np.max(a)
max_of_a

10

In [275]:
# Exercise 8.1.4 - Make a variable named mean_of_a to hold the average of all the numbers
#in the above list
    # A: 5.5
    
mean_of_a = np.mean(a)
mean_of_a

5.5

In [276]:
# Exercise 8.1.5 - Make a variable named product_of_a to hold the product of multiplying all 
#the numbers in the above list together
    # A: 3628800

product_of_a = np.product(a)
product_of_a

3628800

In [126]:
# Exercise 8.1.6 - Make a variable named squares_of_a. It should hold each number 
#in a squared like [1, 4, 9, 16, 25...]
    # A: array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])
squares_of_a = np.square(a)
squares_of_a 

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [131]:
# Exercise 8.1.7 - Make a variable named odds_in_a. It should hold only the odd numbers
    # A: array([1, 3, 5, 7, 9])

a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
odds_in_a = (a[a % 2 == 1])
odds_in_a

array([1, 3, 5, 7, 9])

In [132]:
# Exercise 8.1.8 - Make a variable named evens_in_a. It should hold only the evens.
    # A: array([ 2,  4,  6,  8, 10])
    
evens_in_a = (a[a % 2 == 0])
evens_in_a

array([ 2,  4,  6,  8, 10])

In [279]:
# What about life in two dimensions? A list of lists is matrix, a table....
# Setup 2: Consider what it would take to find the sum, min, max, average, 
#sum, product, and list of squares for this list of two lists.

b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])
b

array([[3, 4, 5],
       [6, 7, 8]])

In [141]:
# Exercise 8.2.1 - refactor the following to use numpy. Use sum_of_b as the variable.
# **Hint, you'll first need to make sure that the "b" variable is a numpy array**

sum_of_b = np.sum(b)
sum_of_b


33

In [143]:
# Exercise 8.2.2 - refactor the following to use numpy. 

#Original:
min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  

#My solution with numpy:
min_of_b = np.min(b)
min_of_b

3

In [144]:
# Exercise 8.2.3 - refactor the following maximum calculation to find the answer with numpy.

#Original:
max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])

#My solution with numpy:
max_of_b = np.max(b)
max_of_b

8

In [146]:
# Exercise 8.2.4 - refactor the following using numpy to find the mean of b

#Original:
mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))

#My refactor with numpy
mean_of_b = np.mean(b)
mean_of_b

5.5

In [147]:
# Exercise 8.2.5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.

#Original:
product_of_b = 1
for row in b:
    for number in row:
        product_of_b *= number
        
#My refactor with numpy:
product_of_b = np.product(b)
product_of_b

20160

In [149]:
# Exercise 8.2.6 - refactor the following to use numpy to find the list of squares 

#Original:
squares_of_b = []
for row in b:
    for number in row:
        squares_of_b.append(number**2)
        
#My refactor with numpy:
squares_of_b = np.square(b)
squares_of_b

array([[ 9, 16, 25],
       [36, 49, 64]])

In [151]:
# Exercise 8.2.7 - refactor using numpy to determine the odds_in_b

#Original:
odds_in_b = []
for row in b:
    for number in row:
        if(number % 2 != 0):
            odds_in_b.append(number)
            
#My refactor with numpy:
odds_in_b = (b[b % 2 == 1])
odds_in_b

array([3, 5, 7])

In [153]:
# Exercise 8.2.8 - refactor the following to use numpy to filter only the even numbers

#Original:
evens_in_b = []
for row in b:
    for number in row:
        if(number % 2 == 0):
            evens_in_b.append(number)
            
#My refactor with numpy:
evens_in_b = (b[b % 2 == 0])
evens_in_b

array([4, 6, 8])

In [280]:
# Exercise 8.2.9 - print out the shape of the array b.
b.shape


(2, 3)

In [155]:
# Exercise 8.2.10 - transpose the array b.
np.transpose(b)

array([[3, 6],
       [4, 7],
       [5, 8]])

In [181]:
# Exercise 8.2.11 - reshape the array b to be a single list of 6 numbers. (1 x 6)
b_list =  b.tolist()
b_list
 
new_b_list = []
for x in list(b_list):
    new_b_list.extend(x)
    
new_b_list


[3, 4, 5, 6, 7, 8]

In [281]:
# Exercise 8.2.12 - reshape the array b to be a list of 6 lists,
#each containing only 1 number (6 x 1)
b.reshape(6,1)

array([[3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [283]:
#Setup 3
# HINT, you'll first need to make sure that the "c" variable is a numpy array prior to using numpy array methods.
# Exercise 1 - Find the min, max, sum, and product of c
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [285]:
c = np.array(c)

In [286]:
# Exercise 8.3.1 - Find the min, max, sum, and product of c.
sum_of_c = np.sum(c)
sum_of_c
# A: 72

min_of_c = np.min(c)
min_of_c
# A: -4

max_of_c = np.max(c)
max_of_c
# A: 26

product_of_c = np.product(c)
product_of_c
# A: 137985120

362880

In [287]:
# Exercise 8.3.2 - Determine the standard deviation of c.
    # A: 8.06225774829855

stddev_of_c = np.std(c)
stddev_of_c

2.581988897471611

In [288]:
# Exercise 8.3.3 - Determine the variance of c.
# A: 30

range_of_c = max_of_c - min_of_c
range_of_c

8

In [289]:
# Exercise 8.3.4 - Print out the shape of the array c
c_arr = np.array(c)
print(np.shape(c_arr))

(3, 3)


In [290]:
import numpy as np

# Exercise 8.3.5 - Transpose c and print out transposed result.
#print(np.transpose(c_arr))
c_arr.T

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [291]:
# Exercise 8.3.6 - Get the dot product of the array c with c. 
c_dot = np.dot(c,c)
c_dot

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [294]:
# Exercise 8.3.7 - Write the code necessary to sum up the result of c times c transposed. 
#Answer should be 261

(c.T * c).sum()

261

In [296]:
# Exercise 8.3.8 - Write the code necessary to determine the product of c times c transposed. 
#Answer should be 131681894400.

(c.T *c).prod()


131681894400

In [305]:
d = [
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
]

In [306]:
# Exercise 8.4.1 - Find the sine of all the numbers in d

d = np.array(d)
d
np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [307]:
# Exercise 8.4.2 - Find the cosine of all the numbers in d

np.cos(d)

array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [308]:
# Exercise 8.4.3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [309]:
# Exercise 8.4.4 - Find all the negative numbers in d

d [d < 0]

array([-90, -30, -45, -45])

In [310]:
# Exercise 8.4.5 - Find all the positive numbers in d



d [d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [311]:
# Exercise 8.4.6 - Return an array of only the unique numbers in d.

np.unique(d)

array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [312]:
# Exercise 8.4.7 - Determine how many unique numbers there are in d.

len(np.unique(d))

11

In [318]:
# Exercise 8.4.8 - Print out the shape of d.
d
#array([[ 90,  30,  45,   0, 120, 180],
       #[ 45, -90, -30, 270,  90,   0],
       #[ 60,  45, -45,  90, -45, 180]])
d.shape
#(3, 6)

(3, 6)

In [320]:
# Exercise 8.4.9 - Transpose and then print out the shape of d.

d.T
# array([[ 90,  45,  60],
#        [ 30, -90,  45],
#        [ 45, -30, -45],
#        [  0, 270,  90],
#        [120,  90, -45],
#        [180,   0, 180]])

d.T.shape
#(6, 3)

(6, 3)

In [316]:
# Exercise 8.4.10 - Reshape d into an array of 9 x 2

d.reshape(9,2)

array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])